### ISSUE TITLE
Feature request: overriding containers

### ISSUE THREAD

**Issue by Finesse** [silexphp/Pimple#225] opened 2017-06-04 01:16 UTC
There is a single core and multiple modules in my app. There are common services for the whole app and individual services for the modules in the app. I want to use service containers to lazy-load services. Here how I see it:

```php
use Pimple\Container;

$coreContainer = new Container();
$coreContainer['foo'] = 'foo';
$coreContainer['pdo'] = function() {
    return new \PDO(/* ... */);
};

$module1Container = Container::override($coreContainer);
$module1Container['mailer'] = function() {
    return new \Mailer('server1', 'user1', 'pass1');
};

$module2Container = Container::override($coreContainer);
$module2Container['foo'] = 'foo2';
$module2Container['mailer'] = function() {
    return new \Mailer('server2', 'user2', 'pass2');
};

$coreContainer['foo'] = 'bar';

echo $coreContainer['pdo']; // PDO
echo $coreContainer['mailer']; // service "mailer" not found
echo $module1Container['pdo']; // PDO
echo $module1Container['mailer']; // Mailer
echo $module1Container['foo']; // 'bar'
echo $module2Container['foo']; // 'foo2'
```

I would be really great if Pimple has this feature. I can implement it if you approve an interface.

**Comment by ragboyjr** [comment] 2017-06-05 02:13
@FinesseRus this is very similar to a feature I requested #200. It didn't seem like something Pimple was willing to add.

The main issue is that Pimple doesn't have an interface. If there was an interface we could create all kinds of containers and use decoration to add features. Despite that sounded like an easy solution, an interface doesn't work very well with pimple because of the following example:

```
<?php

$original_c = new Pimple\Container();
$decorated_c = new Pimple\DecoratedContainer($c);
$decorated_c['a'] = function($c) use ($original_c) {
    assert($c === $original_c);
    return ServiceA($c['b']);
};
```

When using decoration with pimple, the service factory function will only be passed with the `original_c` container and all of your features won't available from inside of the defining function which is a serious issue.

I ended up making my own library which solves this issue https://github.com/krakphp/cargo.

The main difference is that when retrieving a service, the interface allows injecting of the container to the service creation function. This allows decorators to pass an instance of themselves down the decoration stack so that the service function that gets called has an instance of the top most decorator. https://github.com/krakphp/cargo/blob/master/src/Container.php#L7

Also, this library does implement container overriding like you propose: https://github.com/krakphp/cargo#delegate-containers

**Comment by FinesseRus** [comment] 2017-06-05 02:23
@ragboyjr Saying 'interface' I mean a way how my feature should look in the code (i.e. method names, separate class or static method, etc.).

I've made this class to meet my feature request:

```php
class OverrideServiceContainer extends Pimple\Container
{
    /**
     * @var Container The overridden container
     */
    protected $overriddenContainer;

    /**
     * {@inheritDoc}
     * @param Container $container A container to override
     */
    public function __construct(Container $container, array $values = array())
    {
        parent::__construct($values);
        $this->overriddenContainer = $container;
    }

    /**
     * {@inheritDoc}
     */
    public function offsetGet($id)
    {
        if (parent::offsetExists($id)) {
            return parent::offsetGet($id);
        } else {
            return $this->overriddenContainer->offsetGet($id);
        }
    }

    /**
     * {@inheritDoc}
     */
    public function offsetExists($id)
    {
        return parent::offsetExists($id) || $this->overriddenContainer->offsetExists($id);
    }

    /**
     * {@inheritDoc}
     */
    public function raw($id)
    {
        try {
            return parent::raw($id);
        } catch (\InvalidArgumentException $e) {
            return $this->overriddenContainer->raw($id);
        }
    }

    /**
     * {@inheritDoc}
     */
    public function extend($id, $callable)
    {
        if (parent::offsetExists($id)) {
            return parent::extend($id, $callable);
        }

        $extended = function ($c) use ($id, $callable) {
            return $callable($this->overriddenContainer[$id], $c);
        };
        $this->offsetSet($id, $extended);
        return $extended;
    }

    /**
     * {@inheritDoc}
     */
    public function keys()
    {
        // It is quicker then array_unique
        $keys = [];

        foreach ($this->overriddenContainer->keys() as $key) {
            $result[$key] = true;
        }
        foreach (parent::keys() as $key) {
            $result[$key] = true;
        }

        return array_keys($keys);
    }
}
```

I works as I described in the question. But I am not sure whether I implemented the `extend` method right.

**Comment by ragboyjr** [comment] 2017-06-05 02:30
@FinesseRus,

That's what I had originally done as well; but if you notice, 

```php
    public function offsetGet($id)
    {
        if (parent::offsetExists($id)) {
            return parent::offsetGet($id);
        } else {
            return $this->overriddenContainer->offsetGet($id);
        }
    }
```

Any services defined in the original container won't see any of the services defined by OverridingContainer. However, for your specific use-case that's probably fine because they likely shouldn't need anything else.

I built a very similar class to yours for one project I was working on:

```
class DelegateContainer extends \Pimple\Container
{
    private $container;

    public function __construct(\Pimple\Container $container) {
        parent::__construct();
        $this->container = $container;
    }

    public function offsetGet($id) {
        if (isset($this->container[$id])) {
            return $this->container[$id];
        }

        return parent::offsetGet($id);
    }
    public function offsetSet($id, $value) {
        if (isset($this->container[$id])) {
            $this->container[$id] = $value;
            return;
        }

        return parent::offsetSet($id, $value);
    }
    public function offsetExists($id) {
        return isset($this->container[$id]) || parent::offsetExists($id);
    }
    public function offsetUnset($id) {
        if (isset($this->container[$id])) {
            unset($this->container[$id]);
            return;
        }

        return parent::offsetUnset($id);
    }
    public function keys() {
        return array_merge(parent::keys(), $this->container->keys());
    }
    public function extend($id, $callable) {
        if (isset($this->container[$id])) {
            return $this->container->extend($id, $callable);
        }

        return parent::extend($id, $callable);
    }
    public function raw($id) {
        if (isset($this->container[$id])) {
            return $this->container->raw($id);
        }

        return parent::raw($id);
    }
}
```

I don't know if I ever used extend within my DelegateContainer, so I'm not sure if it would have any issues comparing it to yours.

**Comment by FinesseRus** [comment] 2017-06-05 02:48
@ragboyjr 

> Any services defined in the original container won't see any of the services defined by OverridingContainer.

This is by design. The overridden container mustn't be affected anyhow by the overriding container.

Your class doesn't allow to override a service in a delegate container:

```php
$coreContainer = new \Pimple\Container([
    'name' => 'core'
]);
$moduleContainer = new DelegateContainer($coreContainer);
$moduleContainer['name'] = 'module';

echo $coreContainer['name']; // 'module'
echo $moduleContainer['name']; // 'module'
```

**Comment by ragboyjr** [comment] 2017-06-05 02:50
@FinesseRus For sure, that was just my specific use case in a project. It worked for what I needed, but you might have different use cases :).

**Comment by fabpot** [comment] 2020-04-24 08:17
Closing this issue as Pimple is now closed for changes and will go into freeze mode.

**Closed by fabpot** 2020-04-24 08:17 UTC
